### ISSUE TITLE
S3 bucket encryption pipeline does not work

### ISSUE THREAD

**Issue by gcasilva** [turbot/flowpipe-mod-aws#69]
**Describe the bug**
Flowpipe s3 bucket encryption pipeline (aws.pipeline.put_s3_bucket_encryption) isn't working we get an 
Error: Internal Error
Bad Request: 'source' not found for function: aws.pipeline.put_s3_bucket_encryption.function.build_encryption_config

**Flowpipe version (`flowpipe -v`)**
Flowpipe: v0.8.0
flowpipe-mod-aws: v0.4.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).
Run a pipeline for s3 bucket encryption (aws.pipeline.put_s3_bucket_encryption)

**Expected behavior**
Flowpipe to encrypt s3 bucket

**Additional context**
Possible fix:

pipelines/s3/put_s3_bucket_encryption.fp file looks for source function as "./pipelines/s3/functions/put_s3_bucket_encryption" but this path doesn't exist in the repo.
The current path in the repo is pipelines/s3/functions/update_s3_bucket_encryption

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/flowpipe-mod-aws/pull/68
